### ISSUE TITLE
Missing IProviderUpdateContextEx interface in solution

### ISSUE THREAD

**Issue by gc1508** [jscott1277/SitecoreAzureSearchProvider#28]

**Comment by gc1508** [comment]
AzureUpdateContext implements the interface IProviderUpdateContextEx, which I am unable to find in the solution. Any idea? Cheers, Gian.

**Comment by jscott1277** [comment]
This interface is in the Sitecore.ContentSearch.dll assembly.  Please make this assembly exists in the lib folder along with all of the other assemblies that the lib folder readme.txt mentions.

https://github.com/jscott1277/SitecoreAzureSearchProvider/blob/master/libs/Readme.txt
